# -*- coding: utf-8 -*-

# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox, QSizePolicy
from PyQt6.QtGui import QFont

class Ui_Dialog(object):
	def setupUi(self, Dialog):
		Dialog.setObjectName('Dialog')
		Dialog.resize(699, 443)
		sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
		Dialog.setSizePolicy(sizePolicy)
		Dialog.setMinimumSize(QtCore.QSize(699, 443))
		Dialog.setMaximumSize(QtCore.QSize(699, 443))
		self.tabWidget = QtWidgets.QTabWidget(Dialog)
		self.tabWidget.setGeometry(QtCore.QRect(0, 0, 700, 443)) # 411
		self.tabWidget.setObjectName('tabWidget')
		self.tab_1 = QtWidgets.QWidget()
		self.tab_1.setObjectName('tab_1')
		self.t1le_1 = QtWidgets.QLineEdit(self.tab_1)
		self.t1le_1.setGeometry(QtCore.QRect(160, 20, 521, 32))
		self.t1le_1.setObjectName('t1le_1')
		self.t1le_2 = QtWidgets.QLineEdit(self.tab_1)
		self.t1le_2.setGeometry(QtCore.QRect(160, 70, 521, 32))
		self.t1le_2.setToolTip('')
		self.t1le_2.setStatusTip('')
		self.t1le_2.setObjectName('t1le_2')
		self.t1le_3 = QtWidgets.QLineEdit(self.tab_1)
		self.t1le_3.setGeometry(QtCore.QRect(160, 120, 521, 32))
		self.t1le_3.setObjectName('t1le_3')
		self.t1l1 = QtWidgets.QLabel(self.tab_1)
		self.t1l1.setGeometry(QtCore.QRect(20, 20, 121, 31))
		self.t1l1.setObjectName('t1l1')
		self.t1l2 = QtWidgets.QLabel(self.tab_1)
		self.t1l2.setGeometry(QtCore.QRect(20, 70, 131, 31))
		self.t1l2.setObjectName('t1l2')
		self.t1l3 = QtWidgets.QLabel(self.tab_1)
		self.t1l3.setGeometry(QtCore.QRect(20, 120, 131, 31))
		self.t1l3.setObjectName('t1l3')
		self.t1l4 = QtWidgets.QLabel(self.tab_1)
		self.t1l4.setGeometry(QtCore.QRect(20, 170, 131, 31))
		self.t1l4.setObjectName('t1l4')
		self.t1cb1 = QtWidgets.QComboBox(self.tab_1)
		self.t1cb1.setGeometry(QtCore.QRect(160, 170, 87, 32))
		self.t1cb1.setObjectName('t1cb1')
		self.t1cb1.addItem('')
		self.t1cb1.addItem('')
		self.t1cb1.addItem('')
		self.t1l5 = QtWidgets.QLabel(self.tab_1)
		self.t1l5.setGeometry(QtCore.QRect(430, 170, 131, 31))
		self.t1l5.setObjectName('t1l5')
		self.t1sb1 = QtWidgets.QSpinBox(self.tab_1)
		self.t1sb1.setGeometry(QtCore.QRect(590, 170, 91, 32))
		self.t1sb1.setMaximum(1000)
		self.t1sb1.setProperty('value', 10)
		self.t1sb1.setObjectName('t1sb1')
		self.t1l6 = QtWidgets.QLabel(self.tab_1)
		self.t1l6.setGeometry(QtCore.QRect(430, 220, 131, 31))
		self.t1l6.setObjectName('t1l6')
		self.t1l7 = QtWidgets.QLabel(self.tab_1)
		self.t1l7.setGeometry(QtCore.QRect(430, 270, 131, 31))
		self.t1l7.setObjectName('t1l7')
		self.t1sb2 = QtWidgets.QSpinBox(self.tab_1)
		self.t1sb2.setGeometry(QtCore.QRect(590, 220, 91, 32))
		self.t1sb2.setMaximum(10000)
		self.t1sb2.setProperty('value', 104) # changed from 48
		self.t1sb2.setObjectName('t1sb2')
		self.t1sb3 = QtWidgets.QSpinBox(self.tab_1)
		self.t1sb3.setGeometry(QtCore.QRect(590, 270, 91, 32))
		self.t1sb3.setMaximum(10000)
		self.t1sb3.setProperty('value', 512)
		self.t1sb3.setObjectName('t1sb3')
		self.t1l8 = QtWidgets.QLabel(self.tab_1)
		self.t1l8.setGeometry(QtCore.QRect(20, 220, 131, 31))
		self.t1l8.setObjectName('t1l8')
		self.t1cb2 = QtWidgets.QComboBox(self.tab_1)
		self.t1cb2.setGeometry(QtCore.QRect(160, 220, 87, 32))
		self.t1cb2.setObjectName('t1cb2')
		self.t1cb2.addItem('')
		self.t1cb2.addItem('')
		self.t1l9 = QtWidgets.QLabel(self.tab_1)
		self.t1l9.setGeometry(QtCore.QRect(20, 270, 131, 31))
		self.t1l9.setObjectName('t1l9')
		self.t1sb4 = QtWidgets.QSpinBox(self.tab_1)
		self.t1sb4.setGeometry(QtCore.QRect(160, 270, 91, 32))
		self.t1sb4.setMaximum(1000)
		self.t1sb4.setProperty('value', 8)
		self.t1sb4.setObjectName('t1sb4')
		self.t1l10 = QtWidgets.QLabel(self.tab_1)
		self.t1l10.setGeometry(QtCore.QRect(20, 320, 131, 31))
		self.t1l10.setObjectName('t1l10')
		self.t1le_4 = QtWidgets.QLineEdit(self.tab_1)
		#self.t1le_4.setGeometry(QtCore.QRect(160, 320, 521, 32)) # V1
		self.t1le_4.setGeometry(QtCore.QRect(160, 320, 241, 32)) # V2
		self.t1le_4.setObjectName('t1le_4')
		# example temps underneath box; added in V2
		self.t1l12 = QtWidgets.QLabel(self.tab_1)
		self.t1l12.setGeometry(QtCore.QRect(160, 345, 191, 31))
		self.t1l12.setObjectName('t1l12')
		# emp corr added in V2
		self.t1l11 = QtWidgets.QLabel(self.tab_1)
		self.t1l11.setGeometry(QtCore.QRect(430, 320, 131, 31))
		self.t1l11.setObjectName('t1l11')
		self.t1cb3 = QtWidgets.QComboBox(self.tab_1)
		self.t1cb3.setGeometry(QtCore.QRect(590, 320, 91, 32))
		self.t1cb3.setObjectName('t1cb3')
		self.t1cb3.addItem('')
		self.t1cb3.addItem('')
		# new submission button on V2
		self.t1_pB_submit = QtWidgets.QPushButton(self.tab_1)
		self.t1_pB_submit.setGeometry(QtCore.QRect(590, 370, 91, 32))
		self.t1_pB_submit.setObjectName('pB_submit')
		self.t1_pB_submit.setFont(QFont('Times', 10))  # Set font family and point size
		self.t1_pB_submit.font().setWeight(QFont.Weight.Bold)  # Set font weight to bold
		#
		self.tabWidget.addTab(self.tab_1, '')
		
		## Tab 2 - old
		# self.tab_2 = QtWidgets.QWidget()
		# self.tab_2.setObjectName('tab_2')
		# self.t2le_1 = QtWidgets.QLineEdit(self.tab_2)
		# self.t2le_1.setGeometry(QtCore.QRect(160, 20, 411, 32))
		# self.t2le_1.setObjectName('t2le_1')
		# self.t2l1 = QtWidgets.QLabel(self.tab_2)
		# self.t2l1.setGeometry(QtCore.QRect(20, 20, 91, 31))
		# self.t2l1.setObjectName('t2l1')
		# self.t2l2 = QtWidgets.QLabel(self.tab_2)
		# self.t2l2.setGeometry(QtCore.QRect(20, 70, 91, 31))
		# self.t2l2.setObjectName('t2l2')
		# self.t2dsb1 = QtWidgets.QDoubleSpinBox(self.tab_2)
		# self.t2dsb1.setGeometry(QtCore.QRect(160, 70, 71, 32))
		# self.t2dsb1.setMaximum(1000000.0)
		# self.t2dsb1.setProperty('value', 298.15)
		# self.t2dsb1.setObjectName('t2dsb1')
		# self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
		# self.pushButton_2.setGeometry(QtCore.QRect(590, 20, 88, 32))
		# self.pushButton_2.setObjectName('pushButton_2')
		# self.tabWidget.addTab(self.tab_2, '')
		
		## Tab 3
		self.tab_3 = QtWidgets.QWidget()
		self.tab_3.setObjectName('tab_3')
		self.t3le_1 = QtWidgets.QLineEdit(self.tab_3)
		self.t3le_1.setGeometry(QtCore.QRect(160, 20, 521, 32))
		self.t3le_1.setObjectName('t3le_1')
		self.t3l1 = QtWidgets.QLabel(self.tab_3)
		self.t3l1.setGeometry(QtCore.QRect(20, 20, 91, 32))
		self.t3l1.setObjectName('t3l1')

		# V2 new stuff in output analyzer tab
		self.t3_pB_load = QtWidgets.QPushButton(self.tab_3)
		self.t3_pB_load.setGeometry(QtCore.QRect(593, 70, 88, 32))
		self.t3_pB_load.setObjectName('pB_load_mout')
		self.t3le_2 = QtWidgets.QLineEdit(self.tab_3)
		self.t3le_2.setGeometry(QtCore.QRect(160, 70, 415, 32))
		self.t3le_2.setObjectName('t3le_2')
		self.t3l2 = QtWidgets.QLabel(self.tab_3)
		self.t3l2.setGeometry(QtCore.QRect(20, 70, 91, 32))
		self.t3l2.setObjectName('t3l2')
		
		self.t3_pB_CCSplot = QtWidgets.QPushButton(self.tab_3)
		self.t3_pB_CCSplot.setGeometry(QtCore.QRect(20, 150, 88, 32))
		self.t3_pB_CCSplot.setObjectName('pB_CCSplot')
		self.t3_pB_Qlplot = QtWidgets.QPushButton(self.tab_3)
		self.t3_pB_Qlplot.setGeometry(QtCore.QRect(20, 200, 88, 32))
		self.t3_pB_Qlplot.setObjectName('pB_Qlplot')
		self.t3_pB_alphaplot = QtWidgets.QPushButton(self.tab_3)
		self.t3_pB_alphaplot.setGeometry(QtCore.QRect(20, 250, 88, 32))
		self.t3_pB_alphaplot.setObjectName('pB_alphaplot')
		
		self.t3_pB_CCSexport = QtWidgets.QPushButton(self.tab_3)
		self.t3_pB_CCSexport.setGeometry(QtCore.QRect(160, 150, 108, 32))
		self.t3_pB_CCSexport.setObjectName('pB_CCSexport')
		self.t3_pB_Qlexport = QtWidgets.QPushButton(self.tab_3)
		self.t3_pB_Qlexport.setGeometry(QtCore.QRect(160, 200, 108, 32))
		self.t3_pB_Qlexport.setObjectName('pB_Qlexport')
		self.t3_pB_alphaexport = QtWidgets.QPushButton(self.tab_3)
		self.t3_pB_alphaexport.setGeometry(QtCore.QRect(160, 250, 108, 32))
		self.t3_pB_alphaexport.setObjectName('pB_alphaexport')
		self.t3_pB_summaryexport = QtWidgets.QPushButton(self.tab_3)
		self.t3_pB_summaryexport.setGeometry(QtCore.QRect(160, 300, 108, 32))
		self.t3_pB_summaryexport.setObjectName('pB_alphaexport')
		
		self.t3l3 = QtWidgets.QLabel(self.tab_3)
		self.t3l3.setGeometry(QtCore.QRect(350, 120, 91, 32))
		self.t3l3.setObjectName('t3l3')
		self.t3le_3 = QtWidgets.QTextEdit(self.tab_3)
		self.t3le_3.setGeometry(QtCore.QRect(350, 150, 331, 250))
		self.t3le_3.setObjectName('t3le_3')
		self.t3le_3.setReadOnly(True)
		self.t3le_3.setFont(QtGui.QFont('courier new')) # keeps spaces true -> nicer display
		# at the end of tab_3
		self.tabWidget.addTab(self.tab_3, '')
		
		## Tab 4
		self.tab_4 = QtWidgets.QWidget()
		self.tab_4.setObjectName('tab_4')
		
		self.t4le_1 = QtWidgets.QLineEdit(self.tab_4)
		self.t4le_1.setGeometry(QtCore.QRect(160, 20, 521, 32))
		self.t4le_1.setObjectName('t4le_1')
		self.t4l1 = QtWidgets.QLabel(self.tab_4)
		self.t4l1.setGeometry(QtCore.QRect(20, 20, 91, 32))
		self.t4l1.setObjectName('t4l1')
		self.t4_pB_load = QtWidgets.QPushButton(self.tab_4)
		self.t4_pB_load.setGeometry(QtCore.QRect(593, 70, 88, 32))
		self.t4_pB_load.setObjectName('pB_load_mout')
		self.t4l3 = QtWidgets.QLabel(self.tab_4)
		self.t4l3.setGeometry(QtCore.QRect(250, 120, 91, 32))
		self.t4l3.setObjectName('t4l3')
		self.t4le_3 = QtWidgets.QTextEdit(self.tab_4)
		self.t4le_3.setGeometry(QtCore.QRect(250, 150, 431, 250))
		self.t4le_3.setObjectName('t4le_3')
		self.t4le_3.setReadOnly(True)
		self.t4le_3.setFont(QtGui.QFont('courier new')) # keeps spaces true -> nicer display
		
		self.t4l2 = QtWidgets.QLabel(self.tab_4)
		self.t4l2.setGeometry(QtCore.QRect(20, 120, 108, 32))
		self.t4l2.setObjectName('t4l2')
		self.t4_cb_export = QtWidgets.QComboBox(self.tab_4)
		self.t4_cb_export.setGeometry(QtCore.QRect(20, 170, 108, 32))
		self.t4_cb_export.setObjectName('t4cb1')
		self.t4_cb_export.addItem('')
		self.t4_cb_export.addItem('')
		self.t4_pB_CCSexport = QtWidgets.QPushButton(self.tab_4)
		self.t4_pB_CCSexport.setGeometry(QtCore.QRect(20, 220, 108, 32))
		self.t4_pB_CCSexport.setObjectName('pB_CCSexport')
		self.t4_pB_Kexport = QtWidgets.QPushButton(self.tab_4)
		self.t4_pB_Kexport.setGeometry(QtCore.QRect(20, 270, 108, 32))
		self.t4_pB_Kexport.setObjectName('pB_Kexport')
		self.tabWidget.addTab(self.tab_4, '')
		
		# really at the end
		# self.pushButton = QtWidgets.QPushButton(Dialog)
		# self.pushButton.setGeometry(QtCore.QRect(612, 410, 88, 34))
		# self.pushButton.setObjectName('pushButton')
		self.retranslateUi(Dialog)
		self.tabWidget.setCurrentIndex(0)
		QtCore.QMetaObject.connectSlotsByName(Dialog)

	def retranslateUi(self, Dialog):
		_translate = QtCore.QCoreApplication.translate
		Dialog.setWindowTitle(_translate('Dialog', 'MobCal-MPI 2.0 Processing Suite'))
		
		## Tab 1
		self.t1le_1.setPlaceholderText(_translate('Dialog', 'File path for folder containing .out/.log to be converted to .mfj'))
		self.t1le_2.setPlaceholderText(_translate('Dialog', '(Optional) .csv file within the Out/Log Directory that contains a list of .out/.log files for conversion to .mfj'))
		self.t1le_3.setText(_translate('Dialog', 'C:\\open3dtools\\bin\\sdf2tinkerxyz.exe '))
		self.t1le_3.setPlaceholderText(_translate('Dialog', 'Directory that sdf2xyz2sdf was installed in if different from default'))
		self.t1l1.setText(_translate('Dialog', 'Out/Log Directory')) # changed from 'Log Directory'
		self.t1l2.setText(_translate('Dialog', 'Out/Log List (.csv)')) # changed from 'Log List'
		self.t1l3.setText(_translate('Dialog', 'sdf2xyz2sdf Directory'))
		self.t1l4.setText(_translate('Dialog', 'Charge'))
		self.t1cb1.setItemText(0, _translate('Dialog', 'calc'))
		self.t1cb1.setItemText(1, _translate('Dialog', 'equal'))
		self.t1cb1.setItemText(2, _translate('Dialog', 'none'))
		self.t1l5.setText(_translate('Dialog', 'Cycles'))
		self.t1l6.setText(_translate('Dialog', 'Velocity Integration'))
		self.t1l7.setText(_translate('Dialog', 'Impact Integration'))
		self.t1l8.setText(_translate('Dialog', 'Buffer Gas'))
		self.t1cb2.setItemText(0, _translate('Dialog', 'He'))
		self.t1cb2.setItemText(1, _translate('Dialog', 'N2'))
		self.t1cb2.setCurrentIndex(1) # set N2 as default
		self.t1l9.setText(_translate('Dialog', 'Number of Cores'))
		# self.t1l10.setText(_translate('Dialog', 'Temperature List')) # V1
		self.t1l10.setText(_translate('Dialog', 'Temperatures')) # V2
		self.t1l11.setText(_translate('Dialog', 'Empirical Correction')) # added in V2
		self.t1cb3.setItemText(0, _translate('Dialog', 'Off'))
		self.t1cb3.setItemText(1, _translate('Dialog', 'On'))
		self.t1cb3.setCurrentIndex(1) # set emp corr 'on' as default
		self.t1_pB_submit.setText(_translate('Dialog', 'Submit'))
		# self.t1le_4.setPlaceholderText(_translate('Dialog', 'Comma delimited list of integer temperature(s) in Kelvin. eg. 298 or 298,400,500')) # V1
		#self.t1le_4.setPlaceholderText(_translate('Dialog', 'T_bath[,T_eff_max,NTgrid] in Kelvin')) # V2
		self.t1le_4.setPlaceholderText(_translate('Dialog', 'T_bath or T_bath,T_eff_max,GridPoints in Kelvin')) # V2 revised for readability
		self.t1l12.setText(_translate('Dialog', ' e.g. 298 or 298,600,30')) # added in V2
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate('Dialog', 'mfj Creator'))
		
		## Tab 2
		# self.t2le_1.setPlaceholderText(_translate('Dialog', '.csv file containing filenames and relative Gibbs energies'))
		# self.t2l1.setText(_translate('Dialog', 'CSV Directory'))
		# self.t2l2.setText(_translate('Dialog', 'Temperature'))
		# self.pushButton_2.setText(_translate('Dialog', 'Select File'))
		# self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate('Dialog', 'Energy Weighter'))
		
		## Tab 3
		self.t3le_1.setPlaceholderText(_translate('Dialog', 'Directory of the .mout file'))
		self.t3le_2.setPlaceholderText(_translate('Dialog', '.mout file to load in'))
		self.t3l1.setText(_translate('Dialog', 'mout Directory'))
		self.t3l2.setText(_translate('Dialog', 'mout File'))
		self.t3l3.setText(_translate('Dialog', 'File Info:'))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate('Dialog', 'analyze single .mout'))
		#self.pushButton.setText(_translate('Dialog', 'Submit'))
		# V2 new stuff in mount analyizer tab
		self.t3_pB_load.setText(_translate('Dialog', 'Load'))
		self.t3_pB_Qlplot.setText(_translate('Dialog', 'plot Q(l)'))
		self.t3_pB_CCSplot.setText(_translate('Dialog', 'plot CCS'))
		self.t3_pB_alphaplot.setText(_translate('Dialog', 'plot mobility'))
		self.t3_pB_Qlexport.setText(_translate('Dialog', 'export Q(l)'))
		self.t3_pB_CCSexport.setText(_translate('Dialog', 'export CCS'))
		self.t3_pB_alphaexport.setText(_translate('Dialog', 'export mobility'))
		self.t3_pB_summaryexport.setText(_translate('Dialog', 'export summary'))
		self.t3_pB_CCSplot.setEnabled(False)
		self.t3_pB_Qlplot.setEnabled(False)
		self.t3_pB_alphaplot.setEnabled(False)
		self.t3_pB_CCSexport.setEnabled(False)
		self.t3_pB_Qlexport.setEnabled(False)
		self.t3_pB_alphaexport.setEnabled(False)
		self.t3_pB_summaryexport.setEnabled(False)

		## Tab 4
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate('Dialog', 'analyze multiple .mout'))
		self.t4le_1.setPlaceholderText(_translate('Dialog', 'File path for folder containing .mout files'))
		self.t4l1.setText(_translate('Dialog', 'mout Directory'))
		self.t4_pB_load.setText(_translate('Dialog', 'Load'))
		self.t4l3.setText(_translate('Dialog', 'File Info:'))
		self.t4_pB_CCSexport.setText(_translate('Dialog', 'export CCS'))
		self.t4_pB_Kexport.setText(_translate('Dialog', 'export mobility'))
		self.t4_pB_CCSexport.setEnabled(False)
		self.t4_pB_Kexport.setEnabled(False)
		
		self.t4l2.setText(_translate('Dialog', 'Export Data:'))
		self.t4_cb_export.setItemText(0, _translate('Dialog', 'low field'))
		self.t4_cb_export.setItemText(1, _translate('Dialog', 'high field'))
		self.t4_cb_export.setCurrentIndex(0) # set 'low field' as default
		self.t4_cb_export.setEnabled(False) # only activate if high field data is available!
